fix(SGV06): convert options to json data
magas-xlr/spa-golden-verbena pull request #12
Opened 2024-09-22 14:31 UTC by matheusbrs

![Screenshot_5](https://github.com/user-attachments/assets/eddd8782-d339-4473-a952-3e63e9847960)
Quando a página carrega, eu crio três opções de enquete (Ótimo, Bom e Não gostei). Essas opções são adicionadas dinamicamente na página como botões de rádio, que o usuário pode selecionar. Cada opção tem um rótulo com seu nome e elas aparecem uma embaixo da outra.

2024-09-23 06:46 UTC, MatheusMFranco commented
Não precisa tirar print do código, eu consigo vê-lo na aba "Files changed".
Os prints são só para a tela ou alguma coisa que não seja possível ver por aqui.

2024-09-23 07:19 UTC, MatheusMFranco requested changes
É bem isso mesmo. Como já foi criado elemento e estrutura de repetição na atividade anterior de validação, acredito que esse conhecimento seja o necessário. Adicionei links de algumas documentações para auxiliar.
 
**Lembre:** Prefira o Google (ou qualquer outro mecanismo de busca) ao ChatGPT ou qualquer outra Inteligência Artificial neste momento de aprendizagem.

![All Mighty](https://media.tenor.com/kylqG4U6ndIAAAAM/all-might-boku-no-hero-academia.gif)

2024-09-23 07:19 UTC, MatheusMFranco commented on index.html
> +                    <div class="field" id="enquete_options">
Adote um padrão de nomenclatura para os **ids**. de todo o projeto Eu recomendo o `kebab-case`, mas você pode usar qualquer um que achar melhor.
Para saber mais:  
- [camelCase](https://developer.mozilla.org/en-US/docs/Glossary/Camel_case);
- [snake_case](https://developer.mozilla.org/en-US/docs/Glossary/Snake_case);
- [kebab-case](https://developer.mozilla.org/en-US/docs/Glossary/Kebab_case).

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +        container.appendChild(document.createElement('br'));
Não existe `<br>` no código original.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +        // Criando o input (radio button)
Se gosta tanto assim de comentários, utilize o [JSDOC](https://jsdoc.app/). Mas para este caso, somente em funções e não em trechos de código aleatórios.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +
E quando eu botar um parâmetro "voto" na _URL_? Está faltando fazer o que a função `receiveURL` faz. Recomendo combinar as duas para não repetir código, já que as duas iniciam quando inicia a página.
Lembre-se nunca de invalidar tarefas anteriores.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +    const options = false;
Agora que vi, se _options_ muda de valor, ele deve ser `let` e não `const`.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +    if (!options) {
Você pode usar o método [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) de um _array_ diretamente aqui e eliminar as linhas 43 a 49.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +
Muitos espaços.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +        input.id = options.id;
Não deveria ser `option` ao invés de `options`?

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +        input.required;
O `required` deve aparecer somente no primeiro input, conforme você tinha feito no HTML.

2024-09-23 07:19 UTC, MatheusMFranco commented on script.js
> +document.addEventListener('DOMContentLoaded', function () {
Utilize [arrow funtion](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

2024-09-24 19:45 UTC, matheusbrs commented on index.html
> +                    <div class="field" id="enquete_options">
check

2024-09-24 19:48 UTC, matheusbrs commented on index.html
> +                    <div class="field" id="enquete_options">
Massa, não sabia que tinhas esses padrões !

2024-09-24 19:49 UTC, matheusbrs commented on script.js
> +        container.appendChild(document.createElement('br'));
😬

2024-09-24 19:49 UTC, matheusbrs commented on script.js
> +        container.appendChild(document.createElement('br'));
check

2024-09-24 19:50 UTC, matheusbrs commented on script.js
> +        // Criando o input (radio button)
check

2024-09-24 19:53 UTC, matheusbrs commented on script.js
> +    const options = false;
check

2024-09-24 20:39 UTC, matheusbrs commented on script.js
> +    if (!options) {
Show

2024-09-24 20:39 UTC, matheusbrs commented on script.js
> +    if (!options) {
check

2024-09-24 20:40 UTC, matheusbrs commented on script.js
> +
check

2024-09-24 20:43 UTC, matheusbrs commented on script.js
> +        input.id = options.id;
check

2024-09-24 20:53 UTC, matheusbrs commented on script.js
> +document.addEventListener('DOMContentLoaded', function () {
check

2024-09-24 20:54 UTC, matheusbrs commented on script.js
> +        input.id = options.id;
check

2024-09-24 20:55 UTC, matheusbrs commented on script.js
> +
check

2024-09-24 20:55 UTC, matheusbrs commented on script.js
> +    if (!options) {
check

2024-09-24 23:48 UTC, matheusbrs commented on script.js
> +
chack

2024-09-26 11:11 UTC, MatheusMFranco requested changes
Perfecto, só mudar a parte da arrow function.

2024-09-26 11:11 UTC, MatheusMFranco commented on script.js
> +document.addEventListener('DOMContentLoaded', start => {
`start`  não está sendo usado, usar `()`

2024-09-26 11:11 UTC, matheusbrs commented on script.js
> +        input.required;
Check

2024-09-27 08:15 UTC, MatheusMFranco requested changes
Para deixar o `input` do lado da `label`, adicione um elemento `section` para agrupar eles.
Primeiro você declara lá na parte onde você cria os outros elementos:
```javascript
const section = document.createElement('section');
```
Depois, lá no final aonde você adiciona os elementos, ao invés de adicionar o `input` e o `label` no container, você adiciona no `section` que você criou:
```javascript
section.appendChild(input); 
section.appendChild(label);
```
Depois adiciona o `section` no `container`.
```javascript
container.appendChild(section);
```
Aí pra deixar mais bonitinho, utilize a classe de espaçamento da direita que o **Bulma** disponibiliza, mas isso lá onde você tava construindo os _inputs_:
```javascript
input.classList.add('mr-2');
```
E está pronto o sorvetinho.

![Majin Boo tomando sorvete](https://64.media.tumblr.com/972018c66b123a63c9d9c7a2e78c880d/tumblr_py9bysEHVj1s15h3qo1_500.gif)

2024-09-27 08:15 UTC, MatheusMFranco commented on script.js
> +        input.setAttribute('required', option.id === 'otimo' ? 'true' : '');
Ao invés de pegar o `id`, melhor pegar o `index`, porque se a primeira opção mudar para outro nome, ferrou.

2024-09-27 08:15 UTC, MatheusMFranco commented on script.js
> +        input.type = 'radio';
Você pode aproveitar que está construindo os atributos do _radio_ e já adicionar a seleção dele:
```javascript
const url = new URL(window.location.href);
const input = document.createElement('input');
const id = option.id;
input.type = 'radio';
input.id = id;
input.checked = url.searchParams.get('vote') === id;
/* resto do código */
```
Eu atribui o valor do `id` numa constante porque ele repete mais de uma vez, além de respeitar a [Lei de Demeter](https://pt.wikipedia.org/wiki/Lei_de_Demeter).

Aí no final você pode **remover** todo este código:
```javascript
const url = new URL(window.location.href);
const parameter = url.searchParams.get('vote');
const radio = document.getElementById(parameter);
if (radio && radio.type === 'radio') {
   radio.checked = true;
   unlockButton();
}
```
E deixar somente este:
```javascript
unlockButton();
```

2024-09-27 08:15 UTC, MatheusMFranco commented on script.js
> +        activateButton.classList.remove('disabled');
Se o elemento com a classe `disabled` não existir, vai dar erro. Sempre adicionar verificação se o elemento existe quando faz uma busca pelo _DOM_:
```javascript
if (activateButton) {
     activateButton.classList.remove('disabled');
}
```

2024-09-27 08:15 UTC, MatheusMFranco commented on script.js
> +        input.value = option.id;
Aqui deveria ser `option.description`.

2024-09-28 22:56 UTC, matheusbrs commented on script.js
> +document.addEventListener('DOMContentLoaded', start => {
check

2024-09-29 13:16 UTC, matheusbrs commented on script.js
> +        activateButton.classList.remove('disabled');
check

2024-10-01 20:11 UTC, matheusbrs commented on script.js
> +        input.value = option.id;
check

2024-10-01 20:15 UTC, matheusbrs commented on script.js
> +        input.type = 'radio';
check

2024-10-01 20:43 UTC, matheusbrs commented on script.js
> +        input.setAttribute('required', option.id === 'otimo' ? 'true' : '');
check

2024-10-02 07:58 UTC, MatheusMFranco requested changes
Existe uma coisa no desenvolvimento de software chamado de [Teste de Regressão](https://pt.wikipedia.org/wiki/Teste_de_regress%C3%A3o). 
Nada mais é que testes que verificam se as funcionalidades anteriores que estavam funcionando não parem de funcionar após uma nova funcionalidade.
Recomendo você sempre testar TODAS as funcionalidades, sempre quando fizer um _commit_.
Mais para frente vamos ver testes unitários e automatizados e isso vai facilitar muito o nosso desenvolvimento.

2024-10-02 07:58 UTC, MatheusMFranco commented on script.js
> +        const activateButton = document.querySelector('disabled');
No HTML não existe elemento `disabled`. Se estiver procurando pela classe, precisa adicionar um ponto antes: `.disabled`.

2024-10-02 07:58 UTC, MatheusMFranco commented on script.js
> +        unlockButton();
Tem que verificar se o botão foi checado para fazer essa parte de desabilitar o botão, sem a condição, o botão ficará sempre habilitado.

2024-10-02 07:58 UTC, MatheusMFranco commented on script.js
> +        const url = new URL(window.location.href);
Deixe as declarações sempre no início do escopo, a não ser que seja algo muuuito específico que depende de outras lógicas para poder ser criada.

2024-10-02 07:58 UTC, MatheusMFranco commented on script.js
> +document.addEventListener('DOMContentLoaded', () => {
Eu notei que este cara está englobando todas as funções, isso não é bom. Deixe a lógica de "iniciou a aplicação" nele, e todo o resto que seja dinâmico, fora.
Isso é um princípio do [SOLID](https://pt.wikipedia.org/wiki/SOLID), o princípio de Responsabilidade Única.

2024-10-02 23:50 UTC, matheusbrs commented on script.js
> +        const activateButton = document.querySelector('disabled');
check

2024-10-03 00:19 UTC, matheusbrs commented on script.js
> +        unlockButton();
check

2024-10-03 00:24 UTC, matheusbrs commented on script.js
> +document.addEventListener('DOMContentLoaded', () => {
check

2024-10-03 00:26 UTC, matheusbrs commented on script.js
> +document.addEventListener('DOMContentLoaded', () => {
check

2024-10-03 08:13 UTC, MatheusMFranco requested changes
![Robin Alegrão](https://pa1.aminoapps.com/7377/7028ebc343bccb11df1afe1c8c79c39ad95be029r1-480-480_hq.gif)

2024-10-03 08:13 UTC, MatheusMFranco commented on script.js
> +        const container = document.getElementById('package-options');
Era melhor do outro jeito mesmo.
Antes ele pegava o elemento apenas uma vez, agora ele está pegando ao menos três vezes (tamanho de `options`).
Como o _container_ não se repete, melhor pegar só uma vez mesmo.

2024-10-03 08:13 UTC, MatheusMFranco commented on script.js
> +
Neste caso, acho melhor usar um `if` do que um ternário. O ternário é interessante quando você tem dois retornos. O `unlockButton` não tem retorno, ele é um [void](https://escolalbk.com.br/glossario/o-que-e-void-tipo-de-dado-em-programacao/).
Como `unlockButton` não tem nenhum "_return_" não se faz sentido armazenar o valor em uma variável, já que não está armazenando valor nenhum.

2024-10-04 07:29 UTC, MatheusMFranco requested changes
Só falta mudar a verificação do primeiro item com o index `0`.
Qualquer dúvida, manda mensagem lá no discord.

2024-10-04 07:29 UTC, MatheusMFranco commented on script.js
> +        options.findIndex(option => option.id === 'input');
Ninguém tá usando o `options.findIndex(option => option.id === 'input');`.

2024-10-04 07:29 UTC, MatheusMFranco commented on script.js
> +options.forEach(option => {
Aqui mesmo você pode pegar o index.
`options.forEach((option, index) => {`

2024-10-05 07:54 UTC, MatheusMFranco approved these changes
Booooooaaaaa!!!

![Joinha pegando fogo](https://www.troublefreepool.com/media/terminator-thumbs-up-gif.250402/full)

2024-10-05 07:57 UTC, MatheusMFranco commented
Closes #10

2024-10-05 07:58 UTC, merged