fix(SGV07): add accessibility to disabled button
magas-xlr/spa-golden-verbena pull request #13
Opened 2024-10-15 01:02 UTC by matheusbrs

CSS
We created the Enabled and Disabled model.<br>

JavaScript
We semantically added the attribute aria-disabled="true" and a condition that, if the input is selected, calls the unlockButton() function.<br>

For the form submission event, we added a listener that reacts when it detects the Enter button action. When triggered, the button variable is called and the click is activated.

2024-10-15 07:39 UTC, MatheusMFranco requested changes
![Dancinha](https://i.pinimg.com/originals/d6/4c/bd/d64cbd5e846f4d579c00460f4dfee0b9.gif)

2024-10-15 07:39 UTC, MatheusMFranco commented on script.js
> +        button.setAttribute('aria-disabled', 'true');
Você pode atribuir a lógica `url.searchParams.get('vote') === id` para uma variável `checked` e tanto o `aria-disabled` e o `input.checked` receberem o valor de checado com base na variável `checked`.

2024-10-15 07:39 UTC, MatheusMFranco commented on script.js
> +        document.addEventListener('keydown', (event) => {
Melhor deixar este evento por fora do função e verificar se o botão estiver desabilitado, porque desta forma ao apertar _Enter_, ele vai vai disparar o evento de _click_. Além disso, e melhor criar uma função para que tanto o _Enter_ quanto o _click_ consumam.

2024-10-18 22:22 UTC, matheusbrs commented on script.js
> +        button.setAttribute('aria-disabled', 'true');
check

2024-10-23 04:36 UTC, matheusbrs commented on script.js
> +        document.addEventListener('keydown', (event) => {
check

2024-10-23 10:07 UTC, MatheusMFranco requested changes
Acho que arrumando essas coisas, já dá pra finalizar! :)

2024-10-23 10:07 UTC, MatheusMFranco commented on script.js
> +    if (hasCheckedFromURL) {
Se o `checked` e o `hasCheckedFromURL` fazem a mesma coisa, por que não usa o `checked` direto?

2024-10-23 10:07 UTC, MatheusMFranco commented on script.js
> +                if (button.getAttribute('aria-disabled') === 'false') {
Dá pra colocar essa condição no mesmo _if_ lá de cima.

2024-10-24 01:49 UTC, matheusbrs commented on script.js
> +    if (hasCheckedFromURL) {
check

2024-10-24 01:49 UTC, matheusbrs commented on script.js
> +                if (button.getAttribute('aria-disabled') === 'false') {
check

2024-10-24 06:25 UTC, MatheusMFranco approved these changes
![Fionna emocionada](https://25.media.tumblr.com/08fa1f577b2b2d27475fe9c43cc1fa52/tumblr_mipj2xV7wL1rbavngo1_1280.gif)

2024-10-24 06:26 UTC, merged