feat(SGV04): feat/get-query-params
magas-xlr/spa-golden-verbena pull request #7
Opened 2024-09-06 18:53 UTC by matheusbrs

![recupera_url](https://github.com/user-attachments/assets/58f2f7f8-3215-48a6-97aa-8abdaa1198ca)
Recupera URL

![Recupera_valor](https://github.com/user-attachments/assets/c778f251-f7e4-4253-a4f4-4a508181eb5c)
Recupera parâmetro da const ulr (value=" ")

![recuperaformulario](https://github.com/user-attachments/assets/0457c065-0203-46ad-bdc4-843dfabc6d15)
Recupera radio do formulario 

![for Each](https://github.com/user-attachments/assets/2c1c1d46-4a65-4b7c-bd82-091f4ef3650a)
Comparamos valor e parametro caso true, seleciona o radio e apaga a mensagem de erro. 

![ssssssss](https://github.com/user-attachments/assets/ecc16d28-eba9-4657-9397-822660caee36)
Function() adicionada ao ouvinte do button

2024-09-07 12:58 UTC, MatheusMFranco requested changes
Show. Pegou os parâmetros da URL, mas não os informados na [atividade](https://github.com/magas-xlr/spa-golden-verbena/issues/6).

2024-09-07 12:58 UTC, MatheusMFranco commented on script.js
> +        const strong = document.createElement('strong');
Mudou a indentação?

2024-09-07 12:58 UTC, MatheusMFranco commented on script.js
> +    let valores = document.querySelectorAll('input[type="radio"]');
Por que `valores` é **let** se ele não é alterado?

2024-09-07 12:58 UTC, MatheusMFranco commented on script.js
> +    const parametro = url.searchParams.get('value');
Por que ele está pegando `value` se na [issue](https://github.com/magas-xlr/spa-golden-verbena/issues/6) é **vote**?

2024-09-07 12:58 UTC, MatheusMFranco commented on script.js
> +document.getElementById('btnEnviar').addEventListener('click', recebeURL(), enviar());
O `recebeURL` tem que ser chamado quando **inicia a página**, não quando o botão é clicado.

2024-09-07 12:58 UTC, MatheusMFranco commented on script.js
> +    document.getElementById('btnEnviar').disabled = false;
O botão está sendo desabilitado antes mesmo da verificação.

2024-09-07 12:58 UTC, MatheusMFranco commented on script.js
> +            document.querySelector('form').removeChild(strong);
Como a lógica tem que ser ao iniciar a página, torna-se impossível ter essa mensagem de erro.

2024-09-08 00:25 UTC, matheusbrs commented on script.js
> +    let valores = document.querySelectorAll('input[type="radio"]');
check

2024-09-08 00:25 UTC, matheusbrs commented on script.js
> +    const parametro = url.searchParams.get('value');
check

2024-09-08 01:15 UTC, matheusbrs commented on script.js
> +document.getElementById('btnEnviar').addEventListener('click', recebeURL(), enviar());
check

2024-09-08 20:02 UTC, matheusbrs commented on script.js
> +        const strong = document.createElement('strong');
check

2024-09-08 20:04 UTC, matheusbrs commented on script.js
> +    document.getElementById('btnEnviar').disabled = false;
check

2024-09-08 20:04 UTC, matheusbrs commented on script.js
> +    document.getElementById('btnEnviar').disabled = false;
check

2024-09-09 08:08 UTC, MatheusMFranco requested changes
Separe a lógica da mensagem de erro a parte, vamos resolver este problema na próxima atividade. Não precisa se preocupar com a aparição e o desaparecimento da mensagem de erro.

2024-09-09 08:08 UTC, MatheusMFranco commented on script.js
> +    const strong = document.querySelector('strong');
Coloque ele dentro da condição.

2024-09-09 08:08 UTC, MatheusMFranco commented on script.js
> +    document.getElementById('btnSend').disabled = false;
Está colocando o **disabled** duas vezes, fora e dentro da condição. Tem que deixar somente dentro da condição.

2024-09-09 08:08 UTC, MatheusMFranco commented on index.html
> +                <button type="button" class="button is-success mt-4" id="btnSend">Enviar voto</button>
Por que tirou o `disabled`? Não há nada no _javascript_ inserindo o `disabled`.

2024-09-09 08:08 UTC, MatheusMFranco commented on script.js
> +    radios.forEach(radio => {
Não precisa ficar caçando na lista de radios toda hora, a informação do radio selecionado já está em `parameter`. Se esta constante pegou o nome do `id `do voto, use ele para pegar o radio diretamente pelo `id`.

2024-09-10 07:58 UTC, MatheusMFranco requested changes
Show, só alterar essas coisas e vamos MESCLAAAAAR!!!

2024-09-10 07:58 UTC, MatheusMFranco commented on script.js
>          document.querySelector('form').removeChild(strong);
Pode comentar isso aqui, a gente resolve na próxima atividade.

2024-09-10 07:58 UTC, MatheusMFranco commented on script.js
> +    const radios = document.querySelectorAll('input[name="voto"]');
Constante não sendo utilizada, pode tirar.

2024-09-10 07:58 UTC, MatheusMFranco commented on script.js
> +            radio.checked = true;
Faltou habilitar o botão de enviar.

2024-09-10 07:58 UTC, MatheusMFranco commented on script.js
> +    if (parameter) {
Não precisa de dois _ifs_, isso aqui já seria o suficiente:
```javascript
const radio = document.getElementById(parameter);
    if (radio) {
       radio.checked = true;
       document.getElementById('btnSend').disabled = false;
    }
```

2024-09-11 07:30 UTC, MatheusMFranco approved these changes
Ok.

2024-09-11 07:30 UTC, merged