fix(SGV05): add disable button
magas-xlr/spa-golden-verbena pull request #9
Opened 2024-09-12 22:14 UTC by matheusbrs

![img1](https://github.com/user-attachments/assets/059fbb9f-7973-4b6e-a3aa-216c0b6a56af)
Como solicitado caso nenhum atividade é reconhecida o sistema matem o botão com a aparência de desabilitado utilizando estilos CSS.

![img2](https://github.com/user-attachments/assets/fd30057a-b1a3-43ff-8caa-3db2d4c8d9e8)
É como esperado caso o usuário selecione alguma opção automaticamente o botão enviar e habilidade utilizando a função remodelButton() que e usada para modificar os parâmetros CSS diretamente pelo javaScript. 

![img3](https://github.com/user-attachments/assets/4e5f62be-3628-4a7c-b199-c608ce0e28ec)
 Caso o usuário acesse o sistema de voto diretamente pela URL, como o parâmetro vote="", o botão e habilidade ao carregar a pagina, sendo assim não veremos a mensagem de erro.

![img4](https://github.com/user-attachments/assets/f808b300-ddcd-444c-a503-e78b7c77e820)
Quando o usuário final clica no botão enviar e não seleciona nenhuma opção de voto, a mensagem de erro é exibida.

![gif1](https://github.com/user-attachments/assets/a765b76f-d7bd-4f8d-806e-0387290997f0)
Por último, mas não menos importante, quando clicamos no botão, ele mostra a mensagem de erro; quando selecionamos alguma opção de voto, a mensagem é desabilitada.

2024-09-13 10:01 UTC, MatheusMFranco requested changes
Leia novamente a [issue](https://github.com/magas-xlr/spa-golden-verbena/issues/8) e analise o que deve ser feito.
Deve-se evitar o atributo `disabled` e simulá-lo com _CSS_, removendo e adicionando a classe com o estilo apropriado.

2024-09-13 10:01 UTC, MatheusMFranco commented on index.html
> +                <button type="button"  class="button is-success mt-4 disabled" id="btnSend">Enviar voto</button>
O intuito da task é não precisar mais do atributo `disabled`.

2024-09-13 10:01 UTC, MatheusMFranco commented on script.js
> +    botao.style.cursor = 'pointer';
Se já tem a _classe_ para dar estilo, não há necessidade do uso de `style`.

2024-09-13 10:01 UTC, MatheusMFranco commented on script.js
>          document.querySelector('form').removeChild(strong);
Se `strong `não existir, essa linha aqui vai dar erro.

2024-09-13 10:01 UTC, MatheusMFranco commented on script.js
>          document.getElementById('btnSend').disabled = false;
Considerando que `remodelButton` é para fazer o efeito de `disabled`, esta linha torna-se redundante,

2024-09-13 10:01 UTC, MatheusMFranco commented on style.css
> +  }
Está com espaço a mais.

2024-09-14 00:42 UTC, matheusbrs commented on script.js
>          document.getElementById('btnSend').disabled = false;
Check

2024-09-14 00:43 UTC, matheusbrs commented on style.css
> +  }
Check

2024-09-14 00:48 UTC, matheusbrs commented on script.js
> +    botao.style.cursor = 'pointer';
Check

2024-09-14 01:03 UTC, matheusbrs commented on script.js
>          document.querySelector('form').removeChild(strong);
Check

2024-09-14 09:16 UTC, MatheusMFranco commented on index.html
> +                <button type="button"  class="button is-success mt-4 disabled" id="btnSend">Enviar voto</button>
Este meu comentário foi equivocado, pois o disabled inserido é a classe CSS e não o atributo.
Muito bem por ter me avisado!

2024-09-14 20:36 UTC, matheusbrs commented on index.html
> +                <button type="button"  class="button is-success mt-4 disabled" id="btnSend">Enviar voto</button>
Check

2024-09-15 17:00 UTC, MatheusMFranco requested changes
Só remover aquela função duplicada que tá bala!

2024-09-15 17:00 UTC, MatheusMFranco commented on script.js
> +    unlockButton();
Função sendo chamada duas vezes.

2024-09-15 22:41 UTC, matheusbrs commented on script.js
> +    unlockButton();
Check

2024-09-16 07:11 UTC, MatheusMFranco approved these changes
![Nice](https://media.tenor.com/H6sjheSkU1wAAAAM/noice-nice.gif)

2024-09-16 07:12 UTC, merged